#!/bin/bash

#Paste your api key directly after the "=" sign
APIKEY=YOURAPIKEYHERE

mkdir -p ~/Pictures/Screenshots
DATE=$(date +"%Y-%m-%d_%H-%M-%S")
FILE="$HOME/Pictures/Screenshots/$DATE.png"
if [ "$#" -gt 1 ];
then echo "Too many arguments supplied!
(Try pantsushot --help)"
	exit;
fi

if [ $# == 0 ];
	then echo "Welcome to the pantsushot!
Option      Description

-f          Takes a fullscreen screenshot (default behavior)
-w          Takes a screenshot of the focused window
-a          Takes a screenshot of a selected area";
	exit;
fi

case $1 in
	-f )
		gnome-screenshot -f $FILE $2;
		paplay /usr/share/sounds/freedesktop/stereo/screen-capture.oga
		;;
	-w )
		gnome-screenshot -w -f $FILE $2;
		paplay /usr/share/sounds/freedesktop/stereo/screen-capture.oga	
		;;
	-a )
		gnome-screenshot -a -f $FILE $2;
		paplay /usr/share/sounds/freedesktop/stereo/screen-capture.oga 
		;;
esac

URL=$(curl -s -F "apikey=$APIKEY" -F "files[]=@$FILE" https://www.shimapan.rocks/upload.php | grep url | awk '{print $2}') 

echo $URL | tr -d '[\\\,"\n]' | xclip -selection c
